[workspace]
resolver = "2"
members = ["crates/strato", "crates/strato-py"]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["sayef <msi.sayef@gmail.com>"]
repository = "https://github.com/sayef/strato"
homepage = "https://github.com/sayef/strato"

[profile.release]
lto = "thin"
codegen-units = 1
debug = 1
