from collections.abc import Mapping, Sequence
from os import PathLike
from typing import Any

from .completr import (
    ChangeSet,
    Client,
    Collection,
    CollectionStats,
    Database,
    Documents,
    Id,
    Index,
    Ingestor,
    Suggestion,
    Transaction,
    Vectors,
)

class AsyncCollection:
    @property
    def name(self) -> str: ...
    async def add(self, documents: Documents, vectors: Vectors | None = None) -> int: ...
    async def delete(self, ids: Sequence[Id]) -> int: ...
    async def optimize(self) -> int | None: ...
    async def stats(self) -> CollectionStats: ...
    def complete(self, query: str, limit: int = 10, **options: Any) -> list[Suggestion]: ...

class AsyncClient:
    """A `Client` whose storage calls are awaitable; constructing it does not block."""
    def __init__(self, url: str = "memory://", **options: Any) -> None: ...
    async def open(self) -> AsyncClient: ...
    async def __aenter__(self) -> AsyncClient: ...
    async def __aexit__(self, *exc: object) -> None: ...
    @property
    def client(self) -> Client: ...
    async def collections(self) -> list[str]: ...
    async def collection(self, name: str) -> AsyncCollection: ...
    async def create_collection(self, name: str, **settings: Any) -> AsyncCollection: ...
    async def get_or_create_collection(self, name: str, **settings: Any) -> AsyncCollection: ...
    async def drop_collection(self, name: str) -> None: ...
    async def sync(self) -> int | None: ...

class AsyncEngine:
    async def sync(self) -> int | None: ...
    def __getattr__(self, name: str) -> Any: ...

class AsyncDatabase:
    """A `Database` whose storage operations are awaitable; constructing it does not block."""
    def __init__(
        self,
        url: str,
        options: Mapping[str, str] | None = None,
        cache_dir: str | PathLike[str] | None = None,
        **build_options: Any,
    ) -> None: ...
    async def open(self) -> AsyncDatabase: ...
    async def __aenter__(self) -> AsyncDatabase: ...
    async def __aexit__(self, *exc: object) -> None: ...
    @property
    def database(self) -> Database: ...
    async def versions(self) -> list[int]: ...
    async def latest_version(self) -> int: ...
    async def index_names(self, version: int | None = None) -> list[str]: ...
    async def manifest(self, version: int | None = None) -> dict[str, Any]: ...
    async def begin(self, version: int | None = None) -> Transaction: ...
    async def commit(self, transaction: Transaction) -> dict[str, Any]: ...
    async def open_index(self, name: str, version: int | None = None, **options: Any) -> Index: ...
    async def engine(self, **options: Any) -> AsyncEngine: ...
    async def submit(self, changes: ChangeSet) -> str: ...
    async def pending_change_sets(self) -> int: ...
    async def compact(self, index: str, **policy: Any) -> int | None: ...
    async def cleanup(self, **policy: Any) -> dict[str, int]: ...
    async def run_ingestor(self, ingestor: Ingestor) -> dict[str, Any]: ...
