from collections.abc import Buffer
from os import PathLike
from typing import Literal, Mapping, Sequence

Document = tuple[int, str, float, Sequence[tuple[str, bool]]]
"""`(id, text, weight, [(alias, is_abbreviation)])`: abbreviations match only exactly."""
MatchKind = Literal["exact", "prefix", "abbreviation", "infix", "fuzzy", "semantic"]
Vectors = Buffer | Sequence[Sequence[float]]
"""One embedding row per document: a float32 array of shape (n, dim), or lists."""
Vector = Buffer | Sequence[float]

__version__: str

class Segment:
    @staticmethod
    def build(
        documents: Sequence[Document],
        deletes: Sequence[int] = ...,
        vectors: Vectors | None = None,
        *,
        min_word_chars: int = 3,
        max_edit_distance: int = 2,
        fuzzy_prefix_chars: int = 7,
        vector_bits: int = 4,
        compact_keys: bool = False,
        build_threads: int = 1,
    ) -> Segment: ...
    @property
    def vector_dim(self) -> int | None: ...
    @property
    def size_bytes(self) -> int: ...
    @staticmethod
    def open(path: str | PathLike[str]) -> Segment: ...
    @staticmethod
    def from_bytes(data: bytes) -> Segment: ...
    def to_bytes(self) -> bytes: ...
    def save(self, path: str | PathLike[str]) -> None: ...
    def ids(self) -> list[int]: ...
    def deletes(self) -> list[int]: ...
    def documents(self) -> list[tuple[int, str, float, list[tuple[str, bool]]]]: ...
    def __len__(self) -> int: ...

class Hit:
    id: int
    score: float
    kind: MatchKind
    layer: str | None

FusionKind = Literal["rrf", "weighted", "lexical_first"]

class HybridHit:
    id: int
    score: float
    kind: MatchKind
    lexical_score: float | None
    semantic_score: float | None
    layer: str | None

class AliasHit:
    id: int
    score: float
    layer: str | None

class Index:
    def __init__(
        self,
        segments: Sequence[Segment],
        max_score: float | None = None,
        popularity_weight: float = 0.4,
        short_query_chars: int = 3,
        short_query_limit: int = 100,
        short_query_cache_entries: int = 10_000,
        vector_threads: int = 1,
    ) -> None: ...
    @property
    def max_score(self) -> float: ...
    @property
    def vector_dim(self) -> int | None: ...
    def vector_search(self, vector: Vector, limit: int = 10) -> list[Hit]: ...
    def hybrid_search(
        self,
        text: str,
        vector: Vector,
        limit: int = 10,
        fusion: FusionKind = "rrf",
        rrf_k: float = 60.0,
        semantic_weight: float = 0.5,
        candidates: int | None = None,
    ) -> list[HybridHit]: ...
    def autocomplete(self, query: str, limit: int = 10) -> list[Hit]: ...
    def search_aliases(self, query: str, limit: int = 10) -> list[AliasHit]: ...
    def get(self, id: int) -> tuple[int, str, float, list[tuple[str, bool]]] | None: ...
    def compact(self) -> Segment: ...
    def segments(self) -> list[Segment]: ...
    def __len__(self) -> int: ...

class Engine:
    def __init__(self, overfetch: int = 2) -> None: ...
    def publish(self, updates: Mapping[str, Index | None]) -> None: ...
    def get(self, name: str) -> Index | None: ...
    def names(self) -> list[str]: ...
    def autocomplete(self, query: str, layers: Sequence[str], limit: int = 10) -> list[Hit]: ...
    def search_aliases(self, query: str, layers: Sequence[str], limit: int = 10) -> list[AliasHit]: ...
    def vector_search(self, vector: Vector, layers: Sequence[str], limit: int = 10) -> list[Hit]: ...
    def hybrid_search(
        self,
        text: str,
        vector: Vector,
        layers: Sequence[str],
        limit: int = 10,
        fusion: FusionKind = "rrf",
        rrf_k: float = 60.0,
        semantic_weight: float = 0.5,
        candidates: int | None = None,
    ) -> list[HybridHit]: ...

class Store:
    def __init__(
        self, url: str, options: Mapping[str, str] | None = None, cache_dir: str | PathLike[str] | None = None
    ) -> None: ...
    def prune_cache(self, keep: Sequence[str]) -> int: ...
    def get(self, key: str) -> bytes: ...
    def put(self, key: str, data: bytes) -> None: ...
    def put_if_absent(self, key: str, data: bytes) -> bool: ...
    def delete(self, key: str) -> None: ...
    def list(self, prefix: str = "") -> list[str]: ...
    def put_segment(self, key: str, segment: Segment) -> None: ...
    def get_segment(self, key: str) -> Segment: ...

class ConflictError(Exception): ...

class Transaction:
    @property
    def read_version(self) -> int: ...
    def append(
        self, index: str, documents: Sequence[Document], deletes: Sequence[int] = ..., vectors: Vectors | None = None
    ) -> None: ...
    def overwrite(self, index: str, documents: Sequence[Document], vectors: Vectors | None = None) -> None: ...
    def drop_index(self, index: str) -> None: ...
    def set_max_score(self, index: str, max_score: float) -> None: ...
    def set_metadata(self, key: str, value: str | None) -> None: ...
    def strict(self, strict: bool = True) -> None: ...
    def max_retries(self, retries: int) -> None: ...
    def commit(self) -> dict: ...

class Lease:
    @property
    def generation(self) -> int: ...
    def renew(self, ttl_seconds: float) -> bool: ...
    def release(self) -> None: ...

class Dataset:
    def __init__(
        self,
        url: str,
        options: Mapping[str, str] | None = None,
        cache_dir: str | PathLike[str] | None = None,
        *,
        min_word_chars: int = 3,
        max_edit_distance: int = 2,
        fuzzy_prefix_chars: int = 7,
        vector_bits: int = 4,
        compact_keys: bool = False,
        build_threads: int = 1,
    ) -> None: ...
    def versions(self) -> list[int]: ...
    def latest_version(self) -> int: ...
    def manifest(self, version: int | None = None) -> dict: ...
    def begin(self, version: int | None = None) -> Transaction: ...
    def load_index(
        self,
        name: str,
        version: int | None = None,
        popularity_weight: float = 0.4,
        short_query_chars: int = 3,
        short_query_limit: int = 100,
        short_query_cache_entries: int = 10_000,
        vector_threads: int = 1,
    ) -> Index: ...
    def compact(
        self,
        index: str,
        fanout: int = 4,
        max_segments: int = 16,
        max_hidden_fraction: float = 0.25,
        until_done: bool = False,
    ) -> int | None: ...
    def cleanup(self, keep_versions: int = 10, older_than_seconds: float = 3600.0) -> dict[str, int]: ...
    def acquire_lease(self, name: str, owner: str, ttl_seconds: float) -> Lease | None: ...
    def submit(self, batch: Batch) -> str: ...
    def pending_batches(self) -> int: ...

class Batch:
    def __init__(self) -> None: ...
    def upsert(self, index: str, documents: Sequence[Document], vectors: Vectors | None = None) -> None: ...
    def delete(self, index: str, ids: Sequence[int]) -> None: ...

class Writer:
    def __init__(
        self, dataset: Dataset, owner: str, lease_ttl_seconds: float = 30.0, max_batches: int = 1000, compact: bool = True
    ) -> None: ...
    @property
    def is_leader(self) -> bool: ...
    def run_once(self) -> dict: ...
    def release(self) -> None: ...

class Follower:
    def __init__(
        self,
        dataset: Dataset,
        engine: Engine,
        popularity_weight: float = 0.4,
        short_query_chars: int = 3,
        short_query_limit: int = 100,
        short_query_cache_entries: int = 10_000,
        vector_threads: int = 1,
        group_separator: str | None = None,
    ) -> None: ...
    @property
    def version(self) -> int: ...
    def sync(self) -> int | None: ...
